This is makeindex, version 2.16 [MiKTeX 25.3 Portable].
Scanning style file ./main.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file main.acn....done (122 entries accepted, 0 rejected).
Sorting entries....done (919 comparisons).
Generating output file main.acr....done (106 lines written, 0 warnings).
Output written in main.acr.
Transcript written in main.alg.
